#' Spark NLP MarianTransformer
#'
#' Spark ML transformer that 
#' See \url{https://nlp.johnsnowlabs.com/api/#com.johnsnowlabs.nlp.annotators.seq2seq.MarianTransformer}
#' 
#' @template roxlate-nlp-algo
#' @template roxlate-inputs-output-params
#' @param lang_id A string representing the target language in the form of >>id<< (id = valid target language ID)
#' @param max_input_length Controls the maximum length for encoder inputs (source language texts) Default: 40
#' @param max_output_length Controls the maximum length for decoder outputs (target language texts) Default: 40
#' @param vocabulary Vocabulary used to encode and decode piece tokens generated by SentencePiece This will be set once the model is created and cannot be changed afterwards
#' 
#' @export
nlp_marian_transformer <- function(x, input_cols, output_col,
                 lang_id = NULL, max_input_length = NULL, max_output_length = NULL, vocabulary = NULL,
                 uid = random_string("marian_transformer_")) {
  UseMethod("nlp_marian_transformer")
}

#' @export
nlp_marian_transformer.spark_connection <- function(x, input_cols, output_col,
                 lang_id = NULL, max_input_length = NULL, max_output_length = NULL, vocabulary = NULL,
                 uid = random_string("marian_transformer_")) {
  args <- list(
    input_cols = input_cols,
    output_col = output_col,
    lang_id = lang_id,
    max_input_length = max_input_length,
    max_output_length = max_output_length,
    vocabulary = vocabulary,
    uid = uid
  ) %>%
  validator_nlp_marian_transformer()

  jobj <- sparklyr::spark_pipeline_stage(
    x, "com.johnsnowlabs.nlp.annotators.seq2seq.MarianTransformer",
    input_cols = args[["input_cols"]],
    output_col = args[["output_col"]],
    uid = args[["uid"]]
  ) %>%
    sparklyr::jobj_set_param("setLangId", args[["lang_id"]])  %>%
    sparklyr::jobj_set_param("setMaxInputLength", args[["max_input_length"]])  %>%
    sparklyr::jobj_set_param("setMaxOutputLength", args[["max_output_length"]])  %>%
    sparklyr::jobj_set_param("setVocabulary", args[["vocabulary"]]) 

  new_nlp_marian_transformer(jobj)
}

#' @export
nlp_marian_transformer.ml_pipeline <- function(x, input_cols, output_col,
                 lang_id = NULL, max_input_length = NULL, max_output_length = NULL, vocabulary = NULL,
                 uid = random_string("marian_transformer_")) {

  stage <- nlp_marian_transformer.spark_connection(
    x = sparklyr::spark_connection(x),
    input_cols = input_cols,
    output_col = output_col,
    lang_id = lang_id,
    max_input_length = max_input_length,
    max_output_length = max_output_length,
    vocabulary = vocabulary,
    uid = uid
  )

  sparklyr::ml_add_stage(x, stage)
}

#' @export
nlp_marian_transformer.tbl_spark <- function(x, input_cols, output_col,
                 lang_id = NULL, max_input_length = NULL, max_output_length = NULL, vocabulary = NULL,
                 uid = random_string("marian_transformer_")) {
  stage <- nlp_marian_transformer.spark_connection(
    x = sparklyr::spark_connection(x),
    input_cols = input_cols,
    output_col = output_col,
    lang_id = lang_id,
    max_input_length = max_input_length,
    max_output_length = max_output_length,
    vocabulary = vocabulary,
    uid = uid
  )

  stage %>% sparklyr::ml_transform(x)
}
#' @import forge
validator_nlp_marian_transformer <- function(args) {
  args[["input_cols"]] <- cast_string_list(args[["input_cols"]])
  args[["output_col"]] <- cast_string(args[["output_col"]])
  args[["lang_id"]] <- cast_nullable_string(args[["lang_id"]])
  args[["max_input_length"]] <- cast_nullable_integer(args[["max_input_length"]])
  args[["max_output_length"]] <- cast_nullable_integer(args[["max_output_length"]])
  args[["vocabulary"]] <- cast_nullable_string_list(args[["vocabulary"]])
  args
}

#' Load a pretrained Spark NLP Marian Transformer model
#' 
#' Create a pretrained Spark NLP \code{MarianTransformerModel} model
#' 
#' @template roxlate-pretrained-params
#' @template roxlate-inputs-output-params
#' 
#' @export
nlp_marian_transformer_pretrained <- function(sc, input_cols, output_col,
                                              name = NULL, lang = NULL, remote_loc = NULL) {
  args <- list(
    input_cols = input_cols,
    output_col = output_col
  )
  
  args[["input_cols"]] <- forge::cast_string_list(args[["input_cols"]])
  args[["output_col"]] <- forge::cast_string(args[["output_col"]])
  
  
  model_class <- "com.johnsnowlabs.nlp.annotators.seq2seq.MarianTransformer"
  model <- pretrained_model(sc, model_class, name, lang, remote_loc)
  spark_jobj(model) %>%
    sparklyr::jobj_set_param("setInputCols", args[["input_cols"]]) %>% 
    sparklyr::jobj_set_param("setOutputCol", args[["output_col"]])
  
  new_nlp_marian_transformer(model)
}

nlp_float_params.nlp_marian_transformer <- function(x) {
  return(c())
}
new_nlp_marian_transformer <- function(jobj) {
  sparklyr::new_ml_transformer(jobj, class = "nlp_marian_transformer")
}
